spring:
  config:
    activate:
      on-profile: development
app:
  name: Sentry and logback Dev
  environment: development
---
spring:
  config:
    activate:
      on-profile: production
  devtools:
    add-properties: false
app:
  name: Sentry and logback PRO
  environment: production
---
sentry:
  dsn: ${DSN_KEY}
  release: sentry_long_0.1



